# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  before_all do |lane, options|
    app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_content: options[:key_content],
      is_key_content_base64: true,
    )

    get_certificates
    get_provisioning_profile
    update_code_signing_settings
  end

  lane :build do |options|
    cocoapods

    increment_version_number(version_number: options[:version_number])

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", xcargs: "-allowProvisioningUpdates")
  end

  lane :beta do
    upload_to_testflight
    download_dsyms
    upload_symbols_to_crashlytics
  end

  lane :release do
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
    download_dsyms
    upload_symbols_to_crashlytics
  end
end
